print(True+True)
print(True+False)
print(False+True)
print(False-True)
print(False>True)
print(False==True)
print(True&False)
print(True|False)
print(True^False)
print(True^True)
print(False^False)
print(~True)
print(False>>2)
print(True<<3)
print(True is False)
print(True & False)